# Use the official lightweight Node.js 22 Alpine image
FROM node:26-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json first to leverage Docker caching
COPY package*.json ./

# Install only production dependencies
RUN npm ci --only=production

# Copy the rest of your application source code
COPY . .

# Expose the port your app listens on (change 3000 if your app uses a different port)
EXPOSE 3000

# Define the command to run your app
CMD [ "npm", "run" , "start:prod" ]
