@Host = http://127.0.0.1:9090
POST {{Host}}/authentication/sign-up HTTP/1.1
Content-Type: application/json
Accept-Language: 0

{
    "fullName": "ahmed mohamed",
    "username":"ahmed123",
    "email":"ahmed123@mail.com",
    "password":"@Aa334455",
    "confirmPassword":"@Aa334455",
    "gender":0,
    "phoneNumber":"01008261140",
    "DOB" : "2000-9-9"
}
###

POST {{Host}}/authentication/confirm-email HTTP/1.1
Content-Type: application/json
Accept-Language: 0

{
    "email": "ahmed123@mail.com",
    "otp": "123456"
}
###

POST {{Host}}/authentication/resend-email-otp HTTP/1.1
Content-Type: application/json
Accept-Language: 0

{
    "email": "ahmed123@mail.com"
}
###

POST {{Host}}/authentication/forgot-password HTTP/1.1
Content-Type: application/json
Accept-Language: 0

{
    "email": "ahmed123@mail.com"
}
###

POST {{Host}}/authentication/reset-password HTTP/1.1
Content-Type: application/json
Accept-Language: 0

{
    "email": "ahmed123@mail.com",
    "otp": "123456",
    "password": "@Aa334455",
    "confirmPassword": "@Aa334455"
}
###

POST {{Host}}/authentication/login HTTP/1.1
Content-Type: application/json
Accept-Language: 0

{
    "email":"ahmed123@gmail.com",
    "password":"@Aa334455"
}

###

POST {{Host}}/authentication/rotate-token HTTP/1.1
Content-Type: application/json
Accept-Language: 0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWJkNzIzOWVkNGUwZDc1NTg2Nzk3NDYiLCJhdWQiOjAsInNpZCI6Ijk5NDc0ZDBhLWNkZGItNGE1ZC1iNDc0LThkOGQxYjQ5MWI0MyIsInNlc3Npb25FeHAiOjE4MjIzMzY3NzEsImlhdCI6MTc5MDgwMDc3MSwiZXhwIjoxODIyMzM2NzcxLCJqdGkiOiI1YzRiM2RjZi1mMjQzLTQxYjctYTYwOC0zNTU4NmViNWFhMTIifQ.EMrZ0WkvxEl_x_fUSgW2_MXQvkQ9DoXKRwQcScXgWmc

{
    "expireToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWJkM2MxZGJlYzE3MmM1ZDQ0OGUwZTkiLCJhdWQiOjAsImlzc3VlciI6Imh0dHA6Ly8xMjcuMC4wLjE6OTA5MCIsImlhdCI6MTc5MDc5NzM0MSwiZXhwIjoxNzkwNzk4MjQxLCJqdGkiOiIwZjJlZmRlOS05MWI1LTQwNWUtOGFjOS1jNzIyNjk5YzI5MmUifQ.9fuz2uFSzMsgooWiCcJnTizK6-hg-MYrgH70Ji3NQnI"
}

###

GET  {{Host}}/authentication/profile HTTP/1.1
Content-Type: application/json
Accept-Language: 1
Authorization: Bearer 

###
POST {{Host}}/authentication/logout HTTP/1.1
Content-Type: application/json
Accept-Language: 0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWJkNzIzOWVkNGUwZDc1NTg2Nzk3NDYiLCJhdWQiOjAsImlzc3VlciI6Imh0dHA6Ly8xMjcuMC4wLjE6OTA5MCIsImlhdCI6MTc5MDk3Mjc3MywiZXhwIjoxNzkwOTczNjczLCJqdGkiOiI4N2ExNTBjOS0wZWEzLTQ2Y2QtOWEzMy0xMjg0MTE0YTE1OWMifQ.lN4QfYHPZOsxHoHR-MoueTHMmes30Wk7aItxCtKZvP0
