### signup
POST http://127.0.0.1:9090/authentication/signup
Content-Type: application/json

{
    "fullName": "Abdulrhman Mohamed",
    "username": "ahmed123",
    "email": "ahmed123@gmail.com",
    "password": "Abdul@123",
    "gender":0,
    "phoneNumber":"01008261140",
    "confirmPassword": "Abdul@123",
    "DOB": "2000-01-01"
}
### login
POST http://127.0.0.1:9090/authentication/login
Content-Type:  application/json

{
    "email": "ahmed123@gmail.com",
    "password": "Abdul@123"
}

### profile
GET  http://127.0.0.1:9090/authentication/profile
content-Type:  application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWFlYTVkMjVjYmMwOWYyMjc5NzlkY2IiLCJpYXQiOjE3ODk4MzE4ODgsImV4cCI6MTc4OTgzMjc4OH0.d_kmsB94JQKkmICLalbIb6-iXUnJIBl_RNWaZbTy23M

### rotate
POST   http://127.0.0.1:9090/authentication/rotate-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWFlYTVkMjVjYmMwOWYyMjc5NzlkY2IiLCJpYXQiOjE3ODk4MzE5MDcsImV4cCI6MTgyMTM2NzkwN30.wsMCX0a-8Byk6ZbIlw0Q60qo0xUI7r4HZXKCXAgOZuw