@Host = http://127.0.0.1:9090

###
GET {{Host}}/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWNhNjY0YjAzNjdhYjVmMWRkMDY2NWQiLCJhdWQiOiJVU0VSIiwiaXNzdWVyIjoiaHR0cDovLzEyNy4wLjAuMTo5MDkwIiwiaWF0IjoxNzkxNjY1OTA4LCJleHAiOjE3OTE2NjY4MDgsImp0aSI6IjRiMDk5ZTM1LTI2ZmItNDEwZS05MGZlLWZhMzFmNTc2M2Q0NCJ9.lgBXzIGGjVyujDGp5oTMWBXRzfwHgQJyS4Z0RkJp_XY